apiVersion: apps/v1
kind: Deployment
metadata:
  name: keyforge-frontend
  namespace: keyforge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyforge-frontend
  template:
    metadata:
      labels:
        app: keyforge-frontend
    spec:
      containers:
      - name: frontend
        image: keyforge-frontend:latest
        imagePullPolicy: Never  # Use local image from k3s import
        ports:
        - containerPort: 3001
          name: http
        env:
        # Frontend API URL - points to NodePort service
        - name: VITE_API_BASE
          valueFrom:
            configMapKeyRef:
              name: keyforge-config
              key: VITE_API_BASE
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 5
