apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: keyforge
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
  clusterIP: None  # Headless service for StatefulSet
